#!/bin/bash

# Exit if network device "tun0" exists.
ip link show dev tun0 >/dev/null 2>&1 && exit 0

# Exit if we're not starting "wlan0".
[ "$IFACE" = 'wlan0' ] || exit 0

sudo openvpn --daemon piBox --log /home/pi/openvpn.txt --cd /etc/openvpn --config VPN-CERT.ovpn --remote-random
